# Generated by Django 4.0.1 on 2022-02-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadImage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='url_img',
            field=models.ImageField(blank='', default='', upload_to='img/'),
        ),
    ]
