# Generated by Django 4.0.1 on 2022-02-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadImage', '0002_alter_imagemodel_url_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='format_img',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
