# Generated by Django 4.0.1 on 2022-02-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadImage', '0003_alter_imagemodel_format_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='name_img',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
